### ISSUE TITLE
Patched Copy Not Identifying License of Original Copy

### ISSUE THREAD

**Issue by SoaringChris** [ScarletStudy/DGS1-Android-Release#2]
I created a new Japanese Google Play account to purchase this game with. Running the original Japanese Version works fine, but it tells me it can't find my license with the English patch applied

**Comment by wabberz** [comment]
Hi.
Is it possible that you went straight from buying the game to patching within less than 15 minutes? We've been made aware of an issue that starting the patching process within 15 minutes of buying will trigger the refund process, since installing the patch involves uninstalling the original game. Please check your bank statement or your email for hints of a refund having happened here by accident.

If this did indeed happen to you, you should be able to just buy the game again. The second time will be permanent, since PlayStore only allows you to get a refund for an app once.

We will make a note on our patch instructions of that situation and see if we can somehow make the patcher aware of this as well.

Please let me know if that solved your issue.

**Comment by an-error42** [comment]
We were made aware of this behavior just a few hours ago, and updated the website to mention the following:

> Please test the unpatched game immediately after buying for compatibility with your device, as you can get a refund within 15 minutes if it doesn't work. This only works once.
> 
> If it does indeed work, please wait 15 minutes from purchase to patching the game to start the patching process, as the uninstallation of the original game as part of the process might trigger the refund.

To fix this issue:
* Use IrisMobile to restore the original game via the "Restore Original Game" button.
* Uninstall the original game afterward.
* Install DGS again from Play Store.
* **Wait for 20 minutes before attempting to patch the game.**
* Now you can safely patch the game again.

Sorry for the inconvenience, as I said, we were just recently made aware of this fact.

**Comment by SoaringChris** [comment]
Yeah just got the refund email, thanks for the quick responce
