### ISSUE TITLE
I'm stuck on the scarlet study screen

### ISSUE THREAD

**Issue by Sans9955** [ScarletStudy/DGS1-Android-Release#63]
**Device Manufacturer / Model or Emulator / Version??** Moto Z4

**Android Version?** (Kit Kat/Lollipop/Marshmallow/Nougat/Oreo/Pie or the number as in 7.1.0) yes

**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)No

**Is your device rooted?** (If you don't know what this means, then most likely no)
No
### Your issue
I'm stuck on the screen.
**Please describe the issue you are experiencing:**
It's says it's a license error even though I did everything correctly. What do I do because that's the only thing that's stopping me to play the game. I have a screenshot of what it says too. Please help

**Comment by wabberz** [comment]
See #2 
You got the refund since you patched right after buying the game. Check your email for a refund notice to confirm. You will have to uninstall the patch (to reset IrisMobile), then uninstall the game. This will allow you to purchase the game again (since you were refunded, you don't lose any money).

This only happens once, so the second time buying it cannot be refunded.

**Comment by Sans9955** [comment]
Ok thanks.

**Comment by Sans9955** [comment]
I got the second game instead welp because I thought since I had the first one and got refunded why not get the 2nd game welp at least I have the 2nd game now. Good luck translated the 2nd game and have a good day.
